/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MeetTheFounderRouteImport } from './routes/meet-the-founder'
import { Route as MarketHitchRouteImport } from './routes/market-hitch'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as BecomeARetailerRouteImport } from './routes/become-a-retailer'
import { Route as AiByAvanaRouteImport } from './routes/ai-by-avana'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetTheFounderRoute = MeetTheFounderRouteImport.update({
  id: '/meet-the-founder',
  path: '/meet-the-founder',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketHitchRoute = MarketHitchRouteImport.update({
  id: '/market-hitch',
  path: '/market-hitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeARetailerRoute = BecomeARetailerRouteImport.update({
  id: '/become-a-retailer',
  path: '/become-a-retailer',
  getParentRoute: () => rootRouteImport,
} as any)
const AiByAvanaRoute = AiByAvanaRouteImport.update({
  id: '/ai-by-avana',
  path: '/ai-by-avana',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-by-avana': typeof AiByAvanaRoute
  '/become-a-retailer': typeof BecomeARetailerRoute
  '/consulting': typeof ConsultingRoute
  '/market-hitch': typeof MarketHitchRoute
  '/meet-the-founder': typeof MeetTheFounderRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-by-avana': typeof AiByAvanaRoute
  '/become-a-retailer': typeof BecomeARetailerRoute
  '/consulting': typeof ConsultingRoute
  '/market-hitch': typeof MarketHitchRoute
  '/meet-the-founder': typeof MeetTheFounderRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-by-avana': typeof AiByAvanaRoute
  '/become-a-retailer': typeof BecomeARetailerRoute
  '/consulting': typeof ConsultingRoute
  '/market-hitch': typeof MarketHitchRoute
  '/meet-the-founder': typeof MeetTheFounderRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-by-avana'
    | '/become-a-retailer'
    | '/consulting'
    | '/market-hitch'
    | '/meet-the-founder'
    | '/services'
    | '/admin/login'
    | '/brands/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-by-avana'
    | '/become-a-retailer'
    | '/consulting'
    | '/market-hitch'
    | '/meet-the-founder'
    | '/services'
    | '/admin/login'
    | '/brands/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/ai-by-avana'
    | '/become-a-retailer'
    | '/consulting'
    | '/market-hitch'
    | '/meet-the-founder'
    | '/services'
    | '/admin/login'
    | '/brands/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiByAvanaRoute: typeof AiByAvanaRoute
  BecomeARetailerRoute: typeof BecomeARetailerRoute
  ConsultingRoute: typeof ConsultingRoute
  MarketHitchRoute: typeof MarketHitchRoute
  MeetTheFounderRoute: typeof MeetTheFounderRoute
  ServicesRoute: typeof ServicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-the-founder': {
      id: '/meet-the-founder'
      path: '/meet-the-founder'
      fullPath: '/meet-the-founder'
      preLoaderRoute: typeof MeetTheFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-hitch': {
      id: '/market-hitch'
      path: '/market-hitch'
      fullPath: '/market-hitch'
      preLoaderRoute: typeof MarketHitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-retailer': {
      id: '/become-a-retailer'
      path: '/become-a-retailer'
      fullPath: '/become-a-retailer'
      preLoaderRoute: typeof BecomeARetailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-by-avana': {
      id: '/ai-by-avana'
      path: '/ai-by-avana'
      fullPath: '/ai-by-avana'
      preLoaderRoute: typeof AiByAvanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiByAvanaRoute: AiByAvanaRoute,
  BecomeARetailerRoute: BecomeARetailerRoute,
  ConsultingRoute: ConsultingRoute,
  MarketHitchRoute: MarketHitchRoute,
  MeetTheFounderRoute: MeetTheFounderRoute,
  ServicesRoute: ServicesRoute,
  AdminLoginRoute: AdminLoginRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
